<?php 

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2016
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

$GLOBALS['TL_LANG']['tl_user']['customcatalogfeeds'][0] = 'CustomCatalog feeds';
$GLOBALS['TL_LANG']['tl_user']['customcatalogfeeds'][1] = 'Choose the feeds.';
$GLOBALS['TL_LANG']['tl_user']['customcatalogfeedp'][0] = 'CustomCatalog feeds rights';
$GLOBALS['TL_LANG']['tl_user']['customcatalogfeedp'][1] = 'Choose the rights';
